USE INTERFASE_BIZNAGA
GO


--1) CREACION DE ROL EN LA BD REMOTA
--Este rol concentrará los permisos asociados al login del linked server
CREATE ROLE [ROL_FEEDLOT_BIZNAGA_2_INTERFASE_BIZNAGA]				--Nomenclatura ROL_[BDORIGEN]_2_[BDDESTINO]


--2) ALTA DEL LOGIN
CREATE LOGIN [LNK_FEEDLOT_BIZNAGA_2_INTERFASE_BIZNAGA]				--Nomenclatura LNK_[BDORIGEN]_2_[BDDESTINO]
WITH PASSWORD=N'password', 
DEFAULT_DATABASE=[master], 
CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF


--3) ALTA DEL USUARIO EN LA BD
CREATE USER [LNK_FEEDLOT_BIZNAGA_2_INTERFASE_BIZNAGA] 
FOR LOGIN [LNK_FEEDLOT_BIZNAGA_2_INTERFASE_BIZNAGA]


--4) ASOCIACION DEL LOGIN DE LINKED SERVER AL ROL CREADO ANTERIORMENTE
EXEC sp_addrolemember N'ROL_FEEDLOT_BIZNAGA_2_INTERFASE_BIZNAGA', N'LNK_FEEDLOT_BIZNAGA_2_INTERFASE_BIZNAGA'


--5) ASIGNACION DE PERMISOS AL ROL
--Ejemplos tomando las necesidades del procedure SP_WC_FLE4156_WC
GRANT SELECT ON FLE4156 TO ROL_FEEDLOT_BIZNAGA_2_INTERFASE_BIZNAGA
GRANT UPDATE ON FLE4156 TO ROL_FEEDLOT_BIZNAGA_2_INTERFASE_BIZNAGA
