-- Después de ejecutar scripts...
If Not OBJECT_ID('dblog_fix_audit_triggers') Is Null Execute dblog_fix_audit_triggers
-- Antes de ejecutar scripts...
If Not OBJECT_ID('dblog_disable_audit_triggers') Is Null Execute dblog_disable_audit_triggers