--VISTAS
SELECT 'GRANT SELECT ON ' + NAME + ' TO ROL_PERMS_TOTALES_OBJETOS'
FROM SYS.objects
WHERE type = 'V'



--TABLAS
SELECT 'GRANT SELECT ON ' + NAME + ' TO ROL_PERMS_TOTALES_OBJETOS'
FROM SYS.objects
WHERE type = 'U'

SELECT 'GRANT INSERT ON ' + NAME + ' TO ROL_PERMS_TOTALES_OBJETOS'
FROM SYS.objects
WHERE type = 'U'

SELECT 'GRANT UPDATE ON ' + NAME + ' TO ROL_PERMS_TOTALES_OBJETOS'
FROM SYS.objects
WHERE type = 'U'

SELECT 'GRANT DELETE ON ' + NAME + ' TO ROL_PERMS_TOTALES_OBJETOS'
FROM SYS.objects
WHERE type = 'U'



--SPs
SELECT 'GRANT EXECUTE ON ' + NAME + ' TO ROL_PERMS_TOTALES_OBJETOS'
FROM SYS.objects
WHERE type = 'P' AND name NOT LIKE 'dt_%' AND name <> 'sp_tables_info_rowset_64'




--Funciones
SELECT 'GRANT EXECUTE ON ' + NAME + ' TO ROL_PERMS_TOTALES_OBJETOS'
FROM SYS.objects
WHERE type = 'FN'

SELECT 'GRANT SELECT ON ' + NAME + ' TO ROL_PERMS_TOTALES_OBJETOS'
FROM SYS.objects
WHERE type = 'IF'

SELECT 'GRANT SELECT ON ' + NAME + ' TO ROL_PERMS_TOTALES_OBJETOS'
FROM SYS.objects
WHERE type = 'TF'