
--estimamos un file de datos por cada procesador que posee el equipo.


USE master

ALTER DATABASE tempdb MODIFY FILE (NAME = tempdev, FILENAME = 'G:\MSSQL2K8\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\tempdb.mdf')
go
ALTER DATABASE tempdb MODIFY FILE (NAME = templog, FILENAME = 'H:\MSSQL2K8\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\templog.ldf')
go


ALTER DATABASE tempdb ADD FILE ( NAME = N'tempdev1', FILENAME = N'G:\MSSQL2K8\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\tempdb1.ndf' , SIZE = 2097152KB , FILEGROWTH = 102400KB )
GO
ALTER DATABASE tempdb ADD FILE ( NAME = N'tempdev2', FILENAME = N'G:\MSSQL2K8\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\tempdb2.ndf' , SIZE = 2097152KB , FILEGROWTH = 102400KB )
GO
ALTER DATABASE tempdb ADD FILE ( NAME = N'tempdev3', FILENAME = N'G:\MSSQL2K8\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\tempdb3.ndf' , SIZE = 2097152KB , FILEGROWTH = 102400KB )
GO
