USE [tempdb]
GO
CHECKPOINT;
GO
DBCC DROPCLEANBUFFERS;
GO
DBCC FREEPROCCACHE;
GO
DBCC FREESYSTEMCACHE ('ALL');
GO
DBCC FREESESSIONCACHE;
GO
checkpoint
go
DBCC SHRINKFILE (N'tempdev' , XXXXXXXXXX)
GO


/*OTRO PROCEDIMIENTO*/

-- Procedimiento para liberar espacio con shrink la tempdb sin reiniciar el motor
/*
USE [tempdb]
GO
DBCC FREEPROCCACHE
DBCC DROPCLEANBUFFERS 
DBCC FREESYSTEMCACHE ('ALL')
DBCC FREESESSIONCACHE
DBCC SHRINKDATABASE(tempdb, 10)
DBCC SHRINKFILE ('tempdev') 
DBCC SHRINKFILE ('templog') 
GO*/
